version: '3.8'  # Define the docker-compose version

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: